name: Scheduled Fork Sync

on:
  schedule:
    - cron: '0 0 * * *' # Syncs daily at midnight
  workflow_dispatch: # Allows manual trigger button

jobs:
  sync:
    runs-on: ubuntu-latest
    # Explicitly give the built-in GITHUB_TOKEN write access
    permissions:
      contents: write
      actions: write

    steps:
      - name: Back up and Sync Fork
        run: gh repo sync ${{ github.repository }} -b main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
